### ISSUE TITLE
Endpoints that work with users seem to have broken

### ISSUE THREAD

**Issue by RyotaMitaraiWeb** [julkascript/cardflow#45]
It seems like #43 broke a few of the endpoints, since I am receiving 500 internal server error on them. The endpoints that I caught are ``/api/accounts/login``, ``/api/accounts/register``, and ``/api/listings``. It seems like some exception is raised when interacting with users on the back end. I compared the results with code before the merge and the error doesn't appear, so it seems like a regression in the backend.

This is the trace I got from the Docker terminal when I tried to send a POST request to the login endpoint:

```bash
2024-01-16 18:49:38 Internal Server Error: /api/accounts/login/
2024-01-16 18:49:38 Traceback (most recent call last):
2024-01-16 18:49:38   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
2024-01-16 18:49:38     return self.cursor.execute(sql, params)
2024-01-16 18:49:38            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-16 18:49:38 psycopg2.errors.UndefinedColumn: column accounts_user.phone_number does not exist
2024-01-16 18:49:38 LINE 1: ...user"."is_active", "accounts_user"."date_joined", "accounts_...
2024-01-16 18:49:38                                                              ^
2024-01-16 18:49:38 
2024-01-16 18:49:38 
2024-01-16 18:49:38 The above exception was the direct cause of the following exception:
2024-01-16 18:49:38 
2024-01-16 18:49:38 Traceback (most recent call last):
2024-01-16 18:49:38   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
2024-01-16 18:49:38     response = get_response(request)
2024-01-16 18:49:38                ^^^^^^^^^^^^^^^^^^^^^
2024-01-16 18:49:38   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
2024-01-16 18:49:38     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2024-01-16 18:49:38                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-16 18:49:38   File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
2024-01-16 18:49:38     return view_func(*args, **kwargs)
2024-01-16 18:49:38            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-16 18:49:38   File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
2024-01-16 18:49:38     return self.dispatch(request, *args, **kwargs)
2024-01-16 18:49:38            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-16 18:49:38   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
2024-01-16 18:49:38     response = self.handle_exception(exc)
2024-01-16 18:49:38                ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-16 18:49:38   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
2024-01-16 18:49:38     self.raise_uncaught_exception(exc)
2024-01-16 18:49:38   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
2024-01-16 18:49:38     raise exc
2024-01-16 18:49:38   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
2024-01-16 18:49:38     response = handler(request, *args, **kwargs)
2024-01-16 18:49:38                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-16 18:49:38   File "/usr/local/lib/python3.11/site-packages/rest_framework_simplejwt/views.py", line 44, in post
2024-01-16 18:49:38     serializer.is_valid(raise_exception=True)
2024-01-16 18:49:38   File "/usr/local/lib/python3.11/site-packages/rest_framework/serializers.py", line 227, in is_valid
2024-01-16 18:49:38     self._validated_data = self.run_validation(self.initial_data)
2024-01-16 18:49:38                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-16 18:49:38   File "/usr/local/lib/python3.11/site-packages/rest_framework/serializers.py", line 429, in run_validation
2024-01-16 18:49:38     value = self.validate(value)
2024-01-16 18:49:38             ^^^^^^^^^^^^^^^^^^^^
2024-01-16 18:49:38   File "/usr/local/lib/python3.11/site-packages/rest_framework_simplejwt/serializers.py", line 73, in validate
2024-01-16 18:49:38     data = super().validate(attrs)
2024-01-16 18:49:38            ^^^^^^^^^^^^^^^^^^^^^^^
2024-01-16 18:49:38   File "/usr/local/lib/python3.11/site-packages/rest_framework_simplejwt/serializers.py", line 54, in validate
2024-01-16 18:49:38     self.user = authenticate(**authenticate_kwargs)
2024-01-16 18:49:38                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-16 18:49:38   File "/usr/local/lib/python3.11/site-packages/django/views/decorators/debug.py", line 42, in sensitive_variables_wrapper
2024-01-16 18:49:38     return func(*func_args, **func_kwargs)
2024-01-16 18:49:38            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-16 18:49:38   File "/usr/local/lib/python3.11/site-packages/django/contrib/auth/__init__.py", line 77, in authenticate
2024-01-16 18:49:38     user = backend.authenticate(request, **credentials)
2024-01-16 18:49:38            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-16 18:49:38   File "/usr/local/lib/python3.11/site-packages/django/contrib/auth/backends.py", line 46, in authenticate
2024-01-16 18:49:38     user = UserModel._default_manager.get_by_natural_key(username)
2024-01-16 18:49:38            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-16 18:49:38   File "/usr/local/lib/python3.11/site-packages/django/contrib/auth/base_user.py", line 54, in get_by_natural_key
2024-01-16 18:49:38     return self.get(**{self.model.USERNAME_FIELD: username})
2024-01-16 18:49:38            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-16 18:49:38   File "/usr/local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
2024-01-16 18:49:38     return getattr(self.get_queryset(), name)(*args, **kwargs)
2024-01-16 18:49:38            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-16 18:49:38   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 633, in get
2024-01-16 18:49:38     num = len(clone)
2024-01-16 18:49:38           ^^^^^^^^^^
2024-01-16 18:49:38   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 380, in __len__
2024-01-16 18:49:38     self._fetch_all()
2024-01-16 18:49:38   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1881, in _fetch_all
2024-01-16 18:49:38     self._result_cache = list(self._iterable_class(self))
2024-01-16 18:49:38                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-16 18:49:38   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__
2024-01-16 18:49:38     results = compiler.execute_sql(
2024-01-16 18:49:38               ^^^^^^^^^^^^^^^^^^^^^
2024-01-16 18:49:38   File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
2024-01-16 18:49:38     cursor.execute(sql, params)
2024-01-16 18:49:38   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 102, in execute
2024-01-16 18:49:38     return super().execute(sql, params)
2024-01-16 18:49:38            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-16 18:49:38   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
2024-01-16 18:49:38     return self._execute_with_wrappers(
2024-01-16 18:49:38            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-16 18:49:38   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
2024-01-16 18:49:38     return executor(sql, params, many, context)
2024-01-16 18:49:38            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-16 18:49:38   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
2024-01-16 18:49:38     with self.db.wrap_database_errors:
2024-01-16 18:49:38   File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
2024-01-16 18:49:38     raise dj_exc_value.with_traceback(traceback) from exc_value
2024-01-16 18:49:38   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
2024-01-16 18:49:38     return self.cursor.execute(sql, params)
2024-01-16 18:49:38            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-16 18:49:38 django.db.utils.ProgrammingError: column accounts_user.phone_number does not exist
2024-01-16 18:49:38 LINE 1: ...user"."is_active", "accounts_user"."date_joined", "accounts_...
2024-01-16 18:49:38                                                              ^
2024-01-16 18:49:38 
2024-01-16 18:49:38 [16/Jan/2024 16:49:38] "POST /api/accounts/login/ HTTP/1.1" 500 191840
```

This is the body of my request:

```json
{
  "username": "admin",
  "password": "admin"
}
```

This is also the trace for the listing API:

```bash
2024-01-16 18:53:37 [16/Jan/2024 16:53:37] "GET /api/yugioh/cards_in_set/1/ HTTP/1.1" 200 960
2024-01-16 18:53:38 Internal Server Error: /api/listing/
2024-01-16 18:53:38 Traceback (most recent call last):
2024-01-16 18:53:38   File "/usr/local/lib/python3.11/site-packages/django/db/models/fields/related_descriptors.py", line 218, in __get__
2024-01-16 18:53:38     rel_obj = self.field.get_cached_value(instance)
2024-01-16 18:53:38               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-16 18:53:38   File "/usr/local/lib/python3.11/site-packages/django/db/models/fields/mixins.py", line 15, in get_cached_value
2024-01-16 18:53:38     return instance._state.fields_cache[cache_name]
2024-01-16 18:53:38            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
2024-01-16 18:53:38 KeyError: 'user'
2024-01-16 18:53:38 
2024-01-16 18:53:38 During handling of the above exception, another exception occurred:
2024-01-16 18:53:38 
2024-01-16 18:53:38 Traceback (most recent call last):
2024-01-16 18:53:38   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
2024-01-16 18:53:38     return self.cursor.execute(sql, params)
2024-01-16 18:53:38            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-16 18:53:38 psycopg2.errors.UndefinedColumn: column accounts_user.phone_number does not exist
2024-01-16 18:53:38 LINE 1: ...user"."is_active", "accounts_user"."date_joined", "accounts_...
2024-01-16 18:53:38                                                              ^
2024-01-16 18:53:38 
2024-01-16 18:53:38 
2024-01-16 18:53:38 The above exception was the direct cause of the following exception:
2024-01-16 18:53:38 
2024-01-16 18:53:38 Traceback (most recent call last):
2024-01-16 18:53:38   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
2024-01-16 18:53:38     response = get_response(request)
2024-01-16 18:53:38                ^^^^^^^^^^^^^^^^^^^^^
2024-01-16 18:53:38   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
2024-01-16 18:53:38     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2024-01-16 18:53:38                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-16 18:53:38   File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
2024-01-16 18:53:38     return view_func(*args, **kwargs)
2024-01-16 18:53:38            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-16 18:53:38   File "/usr/local/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
2024-01-16 18:53:38     return self.dispatch(request, *args, **kwargs)
2024-01-16 18:53:38            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-16 18:53:38   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
2024-01-16 18:53:38     response = self.handle_exception(exc)
2024-01-16 18:53:38                ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-16 18:53:38   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
2024-01-16 18:53:38     self.raise_uncaught_exception(exc)
2024-01-16 18:53:38   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
2024-01-16 18:53:38     raise exc
2024-01-16 18:53:38   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
2024-01-16 18:53:38     response = handler(request, *args, **kwargs)
2024-01-16 18:53:38                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-16 18:53:38   File "/usr/local/lib/python3.11/site-packages/rest_framework/mixins.py", line 43, in list
2024-01-16 18:53:38     return self.get_paginated_response(serializer.data)
2024-01-16 18:53:38                                        ^^^^^^^^^^^^^^^
2024-01-16 18:53:38   File "/usr/local/lib/python3.11/site-packages/rest_framework/serializers.py", line 768, in data
2024-01-16 18:53:38     ret = super().data
2024-01-16 18:53:38           ^^^^^^^^^^^^
2024-01-16 18:53:38   File "/usr/local/lib/python3.11/site-packages/rest_framework/serializers.py", line 253, in data
2024-01-16 18:53:38     self._data = self.to_representation(self.instance)
2024-01-16 18:53:38                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-16 18:53:38   File "/usr/local/lib/python3.11/site-packages/rest_framework/serializers.py", line 686, in to_representation
2024-01-16 18:53:38     return [
2024-01-16 18:53:38            ^
2024-01-16 18:53:38   File "/usr/local/lib/python3.11/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
2024-01-16 18:53:38     self.child.to_representation(item) for item in iterable
2024-01-16 18:53:38     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-16 18:53:38   File "/usr/local/lib/python3.11/site-packages/rest_framework/serializers.py", line 509, in to_representation
2024-01-16 18:53:38     attribute = field.get_attribute(instance)
2024-01-16 18:53:38                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-16 18:53:38   File "/usr/local/lib/python3.11/site-packages/rest_framework/fields.py", line 446, in get_attribute
2024-01-16 18:53:38     return get_attribute(instance, self.source_attrs)
2024-01-16 18:53:38            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-16 18:53:38   File "/usr/local/lib/python3.11/site-packages/rest_framework/fields.py", line 96, in get_attribute
2024-01-16 18:53:38     instance = getattr(instance, attr)
2024-01-16 18:53:38                ^^^^^^^^^^^^^^^^^^^^^^^
2024-01-16 18:53:38   File "/usr/local/lib/python3.11/site-packages/django/db/models/fields/related_descriptors.py", line 236, in __get__
2024-01-16 18:53:38     rel_obj = self.get_object(instance)
2024-01-16 18:53:38               ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-16 18:53:38   File "/usr/local/lib/python3.11/site-packages/django/db/models/fields/related_descriptors.py", line 199, in get_object
2024-01-16 18:53:38     return qs.get(self.field.get_reverse_related_filter(instance))
2024-01-16 18:53:38            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-16 18:53:38   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 633, in get
2024-01-16 18:53:38     num = len(clone)
2024-01-16 18:53:38           ^^^^^^^^^^
2024-01-16 18:53:38   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 380, in __len__
2024-01-16 18:53:38     self._fetch_all()
2024-01-16 18:53:38   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1881, in _fetch_all
2024-01-16 18:53:38     self._result_cache = list(self._iterable_class(self))
2024-01-16 18:53:38                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-16 18:53:38   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__
2024-01-16 18:53:38     results = compiler.execute_sql(
2024-01-16 18:53:38               ^^^^^^^^^^^^^^^^^^^^^
2024-01-16 18:53:38   File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
2024-01-16 18:53:38     cursor.execute(sql, params)
2024-01-16 18:53:38   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 102, in execute
2024-01-16 18:53:38     return super().execute(sql, params)
2024-01-16 18:53:38            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-16 18:53:38   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
2024-01-16 18:53:38     return self._execute_with_wrappers(
2024-01-16 18:53:38            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-16 18:53:38   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
2024-01-16 18:53:38     return executor(sql, params, many, context)
2024-01-16 18:53:38            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-16 18:53:38   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
2024-01-16 18:53:38     with self.db.wrap_database_errors:
2024-01-16 18:53:38   File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
2024-01-16 18:53:38     raise dj_exc_value.with_traceback(traceback) from exc_value
2024-01-16 18:53:38   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
2024-01-16 18:53:38     return self.cursor.execute(sql, params)
2024-01-16 18:53:38            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-16 18:53:38 django.db.utils.ProgrammingError: column accounts_user.phone_number does not exist
2024-01-16 18:53:38 LINE 1: ...user"."is_active", "accounts_user"."date_joined", "accounts_...
2024-01-16 18:53:38                                                              ^
2024-01-16 18:53:38 
2024-01-16 18:53:38 [16/Jan/2024 16:53:38] "GET /api/listing/?is_sold=false&is_listed=true&card_in_set_id=1 HTTP/1.1" 500 211369
```

**Comment by dinocom33** [comment]
Looks like you haven't done the migrations. New fields have been added in #43.

**Comment by julkascript** [comment]
This can be fixed by deleting your database (postgresql folder in root dir), and as Simeon suggested - run the migrations (or simply just docker-compose down, docker-compose up).

**Comment by RyotaMitaraiWeb** [comment]
yep, forgot that migrations were a thing, thanks for clarifying
